name: Docker CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pip
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: pip install pytest flask-testing

      - name: Run pytest
        run: pytest

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # - name: Install SonarQube Scanner
      #   run: |
      #     wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      #     unzip sonar-scanner-cli-5.0.1.3006-linux.zip 
      #     export PATH="$PATH:$HOME/sonar-scanner-5.0.1.3006-linux/bin"

      # - name: Run SonarQube Analysis
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: "http://http://34.30.27.61:9000/"
      #   run: |
      #     sonar-scanner \
      #       -Dsonar.projectKey=kaizen \
      #       -Dsonar.sources=. \
      #       -Dsonar.host.url=$SONAR_HOST_URL \
      #       -Dsonar.login=$SONAR_TOKEN


      # - name: Build Docker image
      #   run: docker build -t karabalta75/kaizen:1.0 .

      # - name: Docker tag
      #   run: docker tag karabalta75/kaizen:1.0 karabalta75/kaizen:1.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/python-app:2.0.0
          
      # - name: Push image to Docker Hub
      #   run: docker push karabalta75/kaizen:1.0.0
